doc:
  name: website
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/${doc.name}
    username: root
    password: 1qaz2wsx
application:
  generator:
    #数据库类型，当前支持mysql
    dbtype: mysql
    #生成文件的类型,当前支持excel和word和html
    target-file-type: html
    #target-file-type: word
    #使用的模板文件地址
    template-file-path: htmlTemplate2.html
    #template-file-path: wordTemplate.ftl
    #生成文件的目录
    target-file-dir: /Users/jerry/Desktop/
    #黑名单，支持正则表达式
    #blacklist:
    #  - '.*'
    #白名单，支持正则表达式
    #whitelist:
    #  - 't_.*'



